export { default as productRoutes } from "./product.routes";
export { default as supplierRoutes } from "./supplier.routes";
export { default as customerRoutes } from "./customer.routes";
export { default as rolesRoutes } from "./roles.routes";
export { default as userRoutes } from "./user.routes";
export { default as auditLogsRoutes } from "./auditLog.routes";
export { default as settingsRoutes } from "./settings.routes";
export { default as inventoryRoutes } from "./inventory.routes";
export { default as reportRoutes } from "./report.routes";
export { default as dashboardRoutes } from "./ dashboard.routes";
export { default as authRoutes } from "./auth.routes";
